const PDFDocument = require("pdfkit");

const generateReportPDF = (
  orders,
  summary,
  logoPath,
  signatory,
  reportTitle = "SmartBiz Report"
) => {
  const doc = new PDFDocument({ margin: 50 });
  const pageWidth = doc.page.width;

  // 🧢 Logo
  try {
    doc.image(logoPath, pageWidth / 2 - 30, 40, { width: 60 });
  } catch (err) {
    console.error("Logo failed to load:", err.message);
  }

  doc.moveDown(4);
  doc.fontSize(18).text("SmartBiz Custom Solutions", { align: "center" });
  doc.fontSize(12).text(reportTitle, { align: "center" });
  doc.text(`Date: ${new Date().toLocaleDateString()}`, { align: "center" });
  doc.moveDown(2);

  // 📊 Summary
  doc.fontSize(14).text("Summary", { underline: true, align: "center" });
  doc.moveDown(0.5);
  doc.fontSize(12);

  const leftX = 50;
  const rightX = pageWidth / 2 + 20;
  const summaryKeys = Object.keys(summary);
  const half = Math.ceil(summaryKeys.length / 2);

  summaryKeys.forEach((key, index) => {
    const label = key.replace(/([A-Z])/g, " $1").replace(/^./, str => str.toUpperCase());
    const value = typeof summary[key] === "number"
      ? summary[key].toLocaleString("en-US", { maximumFractionDigits: 2 })
      : summary[key];

    const x = index < half ? leftX : rightX;
    const y = doc.y;

    doc.text(`${label}: ${value}`, x, y);
    if (index + 1 === half) doc.moveDown(0.5);
  });

  doc.moveDown(1.5);

  // 📋 Table Header
  doc.x = doc.page.margins.left;
  doc.fontSize(14).text("Order Details", { underline: true, align: "center" });
  doc.moveDown(0.5);

  const columns = [
    { label: "Order ID", x: 50 },
    { label: "Product", x: 120 },
    { label: "Customer", x: 220 },
    { label: "Qty", x: 350 },
    { label: "Status", x: 390 },
    { label: "Date", x: 460 },
  ];

  doc.font("Helvetica-Bold").fontSize(10);
  const headerY = doc.y;
  columns.forEach(col => doc.text(col.label, col.x, headerY));
  doc.moveDown(0.5);

  // 📦 Table Rows
  doc.font("Helvetica").fontSize(10);
  orders.forEach(order => {
    const y = doc.y;
    doc.text(order._id.toString().slice(-6), columns[0].x, y);
    doc.text(order.product?.name || "", columns[1].x, y);
    doc.text(order.customer?.email || "", columns[2].x, y);
    doc.text(order.quantity?.toString() || "", columns[3].x, y);
    doc.text(order.status || "", columns[4].x, y);
    doc.text(new Date(order.createdAt).toLocaleDateString(), columns[5].x, y);
    doc.moveDown(0.5);
  });

  // ✍️ Signature Block
  doc.moveDown(4);
  doc.fontSize(12).text("Approved by:", 50);
  doc.moveDown(1);
  doc.text(signatory.name, 50);
  doc.text(signatory.title, 50);
  doc.moveDown(2);

  // 🖊️ Optional digital signature
  if (signatory.signatureImage) {
    try {
      doc.image(signatory.signatureImage, 50, doc.y, { width: 100 });
      doc.moveDown(2);
    } catch (err) {
      console.error("Signature image failed:", err.message);
      doc.text("Signature: ______________________", 50);
      doc.moveDown(2);
    }
  } else {
    doc.text("Signature: ______________________", 50);
    doc.moveDown(2);
  }

  // 🧷 Optional digital stamp
  if (signatory.stampImage) {
    try {
      doc.image(signatory.stampImage, 50, doc.y, { width: 100 });
      doc.moveDown(2);
    } catch (err) {
      console.error("Stamp image failed:", err.message);
      doc.text("Stamp:     ______________________", 50);
      doc.moveDown(2);
    }
  } else {
    doc.text("Stamp:     ______________________", 50);
    doc.moveDown(2);
  }

  // 📄 Footer
  const footerY = doc.page.height - doc.page.margins.bottom - 40;
  doc.fontSize(10).text("Generated by SmartBiz Admin Dashboard", doc.page.margins.left, footerY, {
    align: "center",
    width: pageWidth - doc.page.margins.left - doc.page.margins.right,
  });
  doc.text(`Report generated on ${new Date().toLocaleString()}`, {
    align: "center",
    width: pageWidth - doc.page.margins.left - doc.page.margins.right,
  });

  return doc;
};

module.exports = generateReportPDF;